[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
bytecode_hash = 'none'
solc = '0.8.18'
remappings = [
    'create2-helpers/=lib/create2-helpers/src/',
    'solady/=lib/solady/src/'
]

[fmt]
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/tree/master/config